-- GLEMI Admin schema for the Supabase project you control.
-- Run once in Supabase > SQL Editor > New query.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  role text not null check (role in ('owner','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_name text not null,
  service text not null,
  appointment_date date not null,
  appointment_time time,
  phone text,
  email text,
  address text,
  total_cad numeric(10,2) default 0,
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled')),
  created_at timestamptz not null default now()
);

create table if not exists public.schedule_settings (
  day_key text primary key,
  enabled boolean not null default true,
  start_time time not null default '08:00',
  end_time time not null default '17:00'
);

insert into public.schedule_settings(day_key,enabled,start_time,end_time) values
('Mon',true,'08:00','17:00'),('Tue',true,'08:00','17:00'),('Wed',true,'08:00','17:00'),
('Thu',true,'08:00','17:00'),('Fri',true,'08:00','17:00'),('Sat',true,'08:00','17:00'),('Sun',false,'08:00','17:00')
on conflict (day_key) do nothing;

create table if not exists public.pricing_settings (
  id bigint generated by default as identity primary key,
  room text not null,
  room_type text not null,
  regular_cad numeric(10,2) not null default 0,
  deep_cad numeric(10,2) not null default 0
);

create table if not exists public.site_settings (
  key text primary key,
  value text
);

alter table public.profiles enable row level security;
alter table public.appointments enable row level security;
alter table public.schedule_settings enable row level security;
alter table public.pricing_settings enable row level security;
alter table public.site_settings enable row level security;

create or replace function public.is_glemi_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active and p.role in ('owner','admin'));
$$;

create or replace function public.is_glemi_owner()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=auth.uid() and p.active and p.role='owner');
$$;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using (public.is_glemi_admin());
drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update to authenticated using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists appointments_admin_all on public.appointments;
create policy appointments_admin_all on public.appointments for all to authenticated using (public.is_glemi_admin()) with check (public.is_glemi_admin());
drop policy if exists schedule_admin_all on public.schedule_settings;
create policy schedule_admin_all on public.schedule_settings for all to authenticated using (public.is_glemi_admin()) with check (public.is_glemi_admin());
drop policy if exists pricing_admin_all on public.pricing_settings;
create policy pricing_admin_all on public.pricing_settings for all to authenticated using (public.is_glemi_admin()) with check (public.is_glemi_admin());
drop policy if exists site_admin_all on public.site_settings;
create policy site_admin_all on public.site_settings for all to authenticated using (public.is_glemi_admin()) with check (public.is_glemi_admin());

-- After creating the two Auth users, run the two INSERT statements shown in GLEMI-NEW-SUPABASE-SETUP.txt.
