-- WELCOME address protection has already been installed in Supabase on 2026-10-10.
-- Do not run the legacy setup SQL: it targets an incompatible schema.
-- Production uses public.promo_redemptions.normalized_address, unique index
-- promo_redemptions_code_address_unique, and public.create_residential_booking.
