-- GLEMI Cleaning & Building Services Ltd.
-- Complete setup for the new Supabase project.
-- Safe to run more than once.

-- 1) Core admin profiles (only Owner + Admin are authorized)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  role text not null check (role in ('owner','admin')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 2) Appointments / bookings
create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  client_name text not null,
  service text not null default 'Residential Cleaning',
  appointment_date date not null,
  appointment_time time,
  phone text,
  email text,
  address text,
  total_cad numeric(10,2) not null default 0,
  status text not null default 'pending' check (status in ('pending','confirmed','cancelled')),
  created_at timestamptz not null default now()
);

alter table public.appointments add column if not exists original_total_cad numeric(10,2);
alter table public.appointments add column if not exists discount_code text;
alter table public.appointments add column if not exists discount_percent numeric(5,2) not null default 0;
alter table public.appointments add column if not exists quote_details jsonb;

-- 3) Working hours used by both Admin and the public calendar
create table if not exists public.schedule_settings (
  day_key text primary key,
  enabled boolean not null default true,
  start_time time not null default '08:00',
  end_time time not null default '17:00'
);

insert into public.schedule_settings(day_key,enabled,start_time,end_time) values
('Mon',true,'08:00','17:00'),
('Tue',true,'08:00','17:00'),
('Wed',true,'08:00','17:00'),
('Thu',true,'08:00','17:00'),
('Fri',true,'08:00','17:00'),
('Sat',true,'08:00','17:00'),
('Sun',false,'08:00','17:00')
on conflict (day_key) do nothing;

-- 4) Residential estimator pricing (CAD)
create table if not exists public.pricing_settings (
  id bigint generated by default as identity primary key,
  room text not null,
  room_type text not null,
  regular_cad numeric(10,2) not null default 0,
  deep_cad numeric(10,2) not null default 0,
  unique(room, room_type)
);

insert into public.pricing_settings(room,room_type,regular_cad,deep_cad) values
('kitchen','regular',67.50,180.00),
('kitchen','large',135.00,225.00),
('bathroom','regular',67.50,90.00),
('bathroom','half',30.00,45.00),
('bathroom','large',90.00,135.00),
('bedroom','regular',22.50,33.75),
('bedroom','large',33.75,45.00),
('living','regular',33.75,56.25),
('living','large',56.25,78.75)
on conflict (room,room_type) do update set
  regular_cad=excluded.regular_cad,
  deep_cad=excluded.deep_cad;

-- 5) Editable site settings used by the admin panel
create table if not exists public.site_settings (
  key text primary key,
  value text
);

insert into public.site_settings(key,value) values
('contact_email','Glemiservices@gmail.com'),
('quote_note','All prices and estimates are subject to verification upon arrival at the property. The final price may be adjusted if the size, condition of the space, or scope of work differs from the information provided when the estimate was requested.'),
('promo_code','WELCOME'),
('promo_percent','10')
on conflict (key) do nothing;

-- 6) Promo code: WELCOME = 10% off first cleaning
create table if not exists public.promo_codes (
  code text primary key,
  discount_percent numeric(5,2) not null check (discount_percent >= 0 and discount_percent <= 100),
  active boolean not null default true,
  first_booking_only boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.promo_codes(code,discount_percent,active,first_booking_only)
values ('WELCOME',10,true,true)
on conflict (code) do update set discount_percent=10, active=true, first_booking_only=true;

create table if not exists public.promo_redemptions (
  id bigint generated by default as identity primary key,
  code text not null references public.promo_codes(code),
  appointment_id bigint references public.appointments(id) on delete set null,
  email_norm text,
  phone_norm text,
  created_at timestamptz not null default now()
);

create index if not exists promo_redemptions_email_idx on public.promo_redemptions(email_norm);
create index if not exists promo_redemptions_phone_idx on public.promo_redemptions(phone_norm);
create index if not exists appointments_date_idx on public.appointments(appointment_date);
create index if not exists appointments_email_idx on public.appointments((lower(email)));

-- 7) Row Level Security
alter table public.profiles enable row level security;
alter table public.appointments enable row level security;
alter table public.schedule_settings enable row level security;
alter table public.pricing_settings enable row level security;
alter table public.site_settings enable row level security;
alter table public.promo_codes enable row level security;
alter table public.promo_redemptions enable row level security;

create or replace function public.is_glemi_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.profiles p
    where p.id=auth.uid() and p.active and p.role in ('owner','admin')
  );
$$;

create or replace function public.is_glemi_owner()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(
    select 1 from public.profiles p
    where p.id=auth.uid() and p.active and p.role='owner'
  );
$$;

-- Re-create policies deterministically
drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated
using (public.is_glemi_admin());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles for update to authenticated
using (id=auth.uid()) with check (id=auth.uid());

drop policy if exists appointments_admin_all on public.appointments;
create policy appointments_admin_all on public.appointments for all to authenticated
using (public.is_glemi_admin()) with check (public.is_glemi_admin());

drop policy if exists schedule_admin_all on public.schedule_settings;
create policy schedule_admin_all on public.schedule_settings for all to authenticated
using (public.is_glemi_admin()) with check (public.is_glemi_admin());

drop policy if exists pricing_admin_all on public.pricing_settings;
create policy pricing_admin_all on public.pricing_settings for all to authenticated
using (public.is_glemi_admin()) with check (public.is_glemi_admin());

drop policy if exists pricing_public_read on public.pricing_settings;
create policy pricing_public_read on public.pricing_settings for select to anon, authenticated using (true);

drop policy if exists site_admin_all on public.site_settings;
create policy site_admin_all on public.site_settings for all to authenticated
using (public.is_glemi_admin()) with check (public.is_glemi_admin());

drop policy if exists promo_admin_read on public.promo_codes;
create policy promo_admin_read on public.promo_codes for select to authenticated
using (public.is_glemi_admin());

drop policy if exists redemption_admin_read on public.promo_redemptions;
create policy redemption_admin_read on public.promo_redemptions for select to authenticated
using (public.is_glemi_admin());

-- 8) Only the two approved emails automatically receive a GLEMI profile
create or replace function public.handle_glemi_auth_user()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_email text := lower(coalesce(new.email,''));
  v_role text;
  v_name text;
begin
  if v_email='glemiservices@gmail.com' then
    v_role := 'owner';
    v_name := coalesce(new.raw_user_meta_data->>'display_name','Yolanda');
  elsif v_email='baltazaranaya@outlook.com' then
    v_role := 'admin';
    v_name := coalesce(new.raw_user_meta_data->>'display_name','Baltazar');
  else
    return new;
  end if;

  insert into public.profiles(id,email,display_name,role,active)
  values(new.id,v_email,v_name,v_role,true)
  on conflict(id) do update set
    email=excluded.email,
    display_name=coalesce(public.profiles.display_name,excluded.display_name),
    role=excluded.role,
    active=true;
  return new;
end;
$$;

drop trigger if exists on_glemi_auth_user_created on auth.users;
create trigger on_glemi_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_glemi_auth_user();

-- Backfill either approved user if already created in Authentication
insert into public.profiles(id,email,display_name,role,active)
select id,lower(email),coalesce(raw_user_meta_data->>'display_name','Baltazar'),'admin',true
from auth.users where lower(email)='baltazaranaya@outlook.com'
on conflict(id) do update set email=excluded.email, role='admin', active=true;

insert into public.profiles(id,email,display_name,role,active)
select id,lower(email),coalesce(raw_user_meta_data->>'display_name','Yolanda'),'owner',true
from auth.users where lower(email)='glemiservices@gmail.com'
on conflict(id) do update set email=excluded.email, role='owner', active=true;

-- 9) Public calendar availability RPC
create or replace function public.get_calendar_availability(p_start_date date, p_end_date date)
returns table(
  day date,
  enabled boolean,
  start_time time,
  end_time time,
  booking_count bigint,
  booked_times text[]
)
language sql
stable
security definer
set search_path=public
as $$
with dates as (
  select d::date as day
  from generate_series(p_start_date::timestamp,p_end_date::timestamp,interval '1 day') d
), mapped as (
  select day,
    case extract(dow from day)::int
      when 0 then 'Sun' when 1 then 'Mon' when 2 then 'Tue' when 3 then 'Wed'
      when 4 then 'Thu' when 5 then 'Fri' when 6 then 'Sat' end as day_key
  from dates
)
select
  m.day,
  coalesce(s.enabled,false) as enabled,
  coalesce(s.start_time,'08:00'::time) as start_time,
  coalesce(s.end_time,'17:00'::time) as end_time,
  count(a.id) filter (where a.status <> 'cancelled')::bigint as booking_count,
  coalesce(array_agg(to_char(a.appointment_time,'HH24:MI') order by a.appointment_time)
    filter (where a.status <> 'cancelled' and a.appointment_time is not null), array[]::text[]) as booked_times
from mapped m
left join public.schedule_settings s on s.day_key=m.day_key
left join public.appointments a on a.appointment_date=m.day
  and a.status <> 'cancelled'
group by m.day,s.enabled,s.start_time,s.end_time
order by m.day;
$$;

grant execute on function public.get_calendar_availability(date,date) to anon, authenticated;

-- 10) Promo eligibility RPC
create or replace function public.check_promo_eligibility(p_code text, p_email text default null, p_phone text default null)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_code text := upper(trim(coalesce(p_code,'')));
  v_email text := lower(trim(coalesce(p_email,'')));
  v_phone text := regexp_replace(coalesce(p_phone,''),'\\D','','g');
  v_promo public.promo_codes%rowtype;
begin
  if v_email='' and v_phone='' then
    return jsonb_build_object('eligible',false,'reason','contact_required');
  end if;
  select * into v_promo from public.promo_codes where code=v_code and active=true;
  if not found then return jsonb_build_object('eligible',false,'reason','invalid_code'); end if;

  if exists(select 1 from public.promo_redemptions r where r.code=v_code and
    ((v_email<>'' and r.email_norm=v_email) or (v_phone<>'' and r.phone_norm=v_phone))) then
    return jsonb_build_object('eligible',false,'reason','already_used');
  end if;

  if v_promo.first_booking_only and exists(
    select 1 from public.appointments a where a.status <> 'cancelled' and
      ((v_email<>'' and lower(coalesce(a.email,''))=v_email) or
       (v_phone<>'' and regexp_replace(coalesce(a.phone,''),'\\D','','g')=v_phone))
  ) then
    return jsonb_build_object('eligible',false,'reason','existing_customer');
  end if;

  return jsonb_build_object('eligible',true,'code',v_code,'discount_percent',v_promo.discount_percent);
end;
$$;

grant execute on function public.check_promo_eligibility(text,text,text) to anon, authenticated;

-- 11) Public residential booking RPC
create or replace function public.create_residential_booking(
  p_client_name text,
  p_date date,
  p_time text,
  p_email text,
  p_phone text,
  p_address text,
  p_original_total numeric,
  p_discount_code text default null,
  p_quote_details jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_time time;
  v_day_key text;
  v_schedule public.schedule_settings%rowtype;
  v_count int;
  v_discount numeric := 0;
  v_code text := upper(trim(coalesce(p_discount_code,'')));
  v_elig jsonb;
  v_final numeric(10,2);
  v_id bigint;
  v_email text := lower(trim(coalesce(p_email,'')));
  v_phone text := regexp_replace(coalesce(p_phone,''),'\\D','','g');
begin
  if trim(coalesce(p_client_name,''))='' or trim(coalesce(p_address,''))='' then
    return jsonb_build_object('ok',false,'reason','missing_required');
  end if;
  if v_email='' and v_phone='' then return jsonb_build_object('ok',false,'reason','contact_required'); end if;
  if p_date is null or p_date < current_date then return jsonb_build_object('ok',false,'reason','invalid_date'); end if;

  begin
    v_time := to_timestamp(trim(p_time),'HH12:MI AM')::time;
  exception when others then
    begin v_time := trim(p_time)::time; exception when others then
      return jsonb_build_object('ok',false,'reason','invalid_time');
    end;
  end;

  if v_time not in ('09:00'::time,'10:00'::time,'12:00'::time,'14:00'::time,'16:00'::time) then
    return jsonb_build_object('ok',false,'reason','invalid_time');
  end if;

  v_day_key := case extract(dow from p_date)::int
    when 0 then 'Sun' when 1 then 'Mon' when 2 then 'Tue' when 3 then 'Wed'
    when 4 then 'Thu' when 5 then 'Fri' when 6 then 'Sat' end;
  select * into v_schedule from public.schedule_settings where day_key=v_day_key;
  if not found or not v_schedule.enabled then return jsonb_build_object('ok',false,'reason','day_unavailable'); end if;
  if v_time < v_schedule.start_time or v_time >= v_schedule.end_time then return jsonb_build_object('ok',false,'reason','time_unavailable'); end if;

  select count(*) into v_count from public.appointments
  where appointment_date=p_date and status <> 'cancelled';
  if v_count>=5 then return jsonb_build_object('ok',false,'reason','day_full'); end if;
  if exists(select 1 from public.appointments where appointment_date=p_date and appointment_time=v_time and status <> 'cancelled') then
    return jsonb_build_object('ok',false,'reason','time_unavailable');
  end if;

  if v_code<>'' then
    v_elig := public.check_promo_eligibility(v_code,nullif(v_email,''),nullif(p_phone,''));
    if coalesce((v_elig->>'eligible')::boolean,false)=false then
      return jsonb_build_object('ok',false,'reason',v_elig->>'reason');
    end if;
    v_discount := coalesce((v_elig->>'discount_percent')::numeric,0);
  end if;

  v_final := round((greatest(coalesce(p_original_total,0),0) * (1-v_discount/100.0))::numeric,2);

  insert into public.appointments(
    client_name,service,appointment_date,appointment_time,phone,email,address,
    original_total_cad,total_cad,discount_code,discount_percent,quote_details,status
  ) values (
    trim(p_client_name),'Residential Cleaning',p_date,v_time,nullif(trim(coalesce(p_phone,'')),''),
    nullif(trim(coalesce(p_email,'')),''),trim(p_address),coalesce(p_original_total,0),v_final,
    nullif(v_code,''),v_discount,p_quote_details,'pending'
  ) returning id into v_id;

  if v_code<>'' and v_discount>0 then
    insert into public.promo_redemptions(code,appointment_id,email_norm,phone_norm)
    values(v_code,v_id,nullif(v_email,''),nullif(v_phone,''));
  end if;

  return jsonb_build_object(
    'ok',true,
    'appointment_id',v_id,
    'final_total',v_final,
    'discount_code',nullif(v_code,''),
    'discount_percent',v_discount
  );
end;
$$;

grant execute on function public.create_residential_booking(text,date,text,text,text,text,numeric,text,jsonb) to anon, authenticated;

-- 12) Public pricing read is intentionally limited to prices only; no internal hourly rate is stored or exposed.

-- Quick verification output
select
  (select count(*) from public.schedule_settings) as schedule_days,
  (select count(*) from public.pricing_settings) as pricing_rows,
  (select count(*) from public.promo_codes where active) as active_promos,
  (select count(*) from public.profiles where active) as active_admin_users;
