
-- GLEMI WELCOME: one 10% redemption per residential address/unit.
-- Run this file once in Supabase SQL Editor.

create table if not exists public.promo_codes (
  code text primary key,
  discount_percent numeric(5,2) not null check (discount_percent >= 0 and discount_percent <= 100),
  active boolean not null default true,
  first_booking_only boolean not null default false
);

insert into public.promo_codes(code,discount_percent,active,first_booking_only)
values ('WELCOME',10,true,false)
on conflict (code) do update
set discount_percent=10, active=true, first_booking_only=false;

create table if not exists public.promo_redemptions (
  id bigint generated by default as identity primary key,
  code text not null,
  appointment_id bigint,
  email_norm text,
  phone_norm text,
  redeemed_at timestamptz not null default now()
);

alter table public.promo_redemptions
  add column if not exists address_key text;

create unique index if not exists promo_redemptions_code_address_uidx
on public.promo_redemptions(code,address_key)
where address_key is not null;

create or replace function public.glemi_normalize_address(
  p_address text,
  p_property_type text default null,
  p_unit_number text default null
)
returns text
language sql
immutable
as $$
  select
    regexp_replace(
      lower(trim(coalesce(p_address,''))),
      '[^a-z0-9]+',
      '',
      'g'
    )
    || case
      when lower(trim(coalesce(p_property_type,''))) in ('apartment','town house')
      then '|unit:' || regexp_replace(lower(trim(coalesce(p_unit_number,''))),'[^a-z0-9]+','','g')
      else '|house'
    end;
$$;

create or replace function public.check_address_promo_eligibility(
  p_code text,
  p_address text,
  p_property_type text default null,
  p_unit_number text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path=public
as $$
declare
  v_code text := upper(trim(coalesce(p_code,'')));
  v_key text;
  v_discount numeric;
begin
  if trim(coalesce(p_address,''))='' then
    return jsonb_build_object('eligible',false,'reason','address_required');
  end if;

  if lower(trim(coalesce(p_property_type,''))) in ('apartment','town house')
     and trim(coalesce(p_unit_number,''))='' then
    return jsonb_build_object('eligible',false,'reason','unit_required');
  end if;

  select discount_percent into v_discount
  from public.promo_codes
  where code=v_code and active=true;

  if not found then
    return jsonb_build_object('eligible',false,'reason','invalid_code');
  end if;

  v_key := public.glemi_normalize_address(p_address,p_property_type,p_unit_number);

  if exists (
    select 1 from public.promo_redemptions
    where code=v_code and address_key=v_key
  ) then
    return jsonb_build_object('eligible',false,'reason','already_used');
  end if;

  return jsonb_build_object(
    'eligible',true,
    'code',v_code,
    'discount_percent',v_discount
  );
end;
$$;

grant execute on function public.check_address_promo_eligibility(text,text,text,text) to anon, authenticated;

-- Replace booking function so eligibility is checked again on the server at FINISH.
create or replace function public.create_residential_booking(
  p_client_name text,
  p_date date,
  p_time text,
  p_email text,
  p_phone text,
  p_address text,
  p_original_total numeric,
  p_discount_code text default null,
  p_quote_details jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_time time;
  v_day_key text;
  v_schedule public.schedule_settings%rowtype;
  v_count int;
  v_discount numeric := 0;
  v_code text := upper(trim(coalesce(p_discount_code,'')));
  v_elig jsonb;
  v_final numeric(10,2);
  v_id bigint;
  v_email text := lower(trim(coalesce(p_email,'')));
  v_phone text := regexp_replace(coalesce(p_phone,''),'\D','','g');
  v_property_type text := coalesce(p_quote_details#>>'{property,type}','');
  v_unit text := coalesce(p_quote_details#>>'{property,unit_number}','');
  v_address_key text;
begin
  if trim(coalesce(p_client_name,''))='' or trim(coalesce(p_address,''))='' then
    return jsonb_build_object('ok',false,'reason','missing_required');
  end if;
  if v_email='' and v_phone='' then
    return jsonb_build_object('ok',false,'reason','contact_required');
  end if;
  if p_date is null or p_date < current_date then
    return jsonb_build_object('ok',false,'reason','invalid_date');
  end if;

  begin
    v_time := to_timestamp(trim(p_time),'HH12:MI AM')::time;
  exception when others then
    begin
      v_time := trim(p_time)::time;
    exception when others then
      return jsonb_build_object('ok',false,'reason','invalid_time');
    end;
  end;

  if v_time not in ('09:00'::time,'10:00'::time,'12:00'::time,'14:00'::time,'16:00'::time) then
    return jsonb_build_object('ok',false,'reason','invalid_time');
  end if;

  v_day_key := case extract(dow from p_date)::int
    when 0 then 'Sun' when 1 then 'Mon' when 2 then 'Tue' when 3 then 'Wed'
    when 4 then 'Thu' when 5 then 'Fri' when 6 then 'Sat' end;

  select * into v_schedule from public.schedule_settings where day_key=v_day_key;
  if not found or not v_schedule.enabled then
    return jsonb_build_object('ok',false,'reason','day_unavailable');
  end if;
  if v_time < v_schedule.start_time or v_time >= v_schedule.end_time then
    return jsonb_build_object('ok',false,'reason','time_unavailable');
  end if;

  select count(*) into v_count
  from public.appointments
  where appointment_date=p_date and status <> 'cancelled';

  if v_count>=5 then
    return jsonb_build_object('ok',false,'reason','day_full');
  end if;

  if exists(
    select 1 from public.appointments
    where appointment_date=p_date
      and appointment_time=v_time
      and status <> 'cancelled'
  ) then
    return jsonb_build_object('ok',false,'reason','time_unavailable');
  end if;

  if v_code<>'' then
    v_elig := public.check_address_promo_eligibility(
      v_code,p_address,v_property_type,nullif(v_unit,'')
    );

    if coalesce((v_elig->>'eligible')::boolean,false)=false then
      return jsonb_build_object('ok',false,'reason',v_elig->>'reason');
    end if;

    v_discount := coalesce((v_elig->>'discount_percent')::numeric,0);
    v_address_key := public.glemi_normalize_address(
      p_address,v_property_type,nullif(v_unit,'')
    );
  end if;

  v_final := round(
    (greatest(coalesce(p_original_total,0),0) * (1-v_discount/100.0))::numeric,
    2
  );

  insert into public.appointments(
    client_name,service,appointment_date,appointment_time,phone,email,address,
    original_total_cad,total_cad,discount_code,discount_percent,quote_details,status
  ) values (
    trim(p_client_name),'Residential Cleaning',p_date,v_time,
    nullif(trim(coalesce(p_phone,'')),''),
    nullif(trim(coalesce(p_email,'')),''),
    trim(p_address),coalesce(p_original_total,0),v_final,
    nullif(v_code,''),v_discount,p_quote_details,'pending'
  )
  returning id into v_id;

  if v_code<>'' and v_discount>0 then
    begin
      insert into public.promo_redemptions(
        code,appointment_id,email_norm,phone_norm,address_key
      ) values (
        v_code,v_id,nullif(v_email,''),nullif(v_phone,''),v_address_key
      );
    exception when unique_violation then
      delete from public.appointments where id=v_id;
      return jsonb_build_object('ok',false,'reason','already_used');
    end;
  end if;

  return jsonb_build_object(
    'ok',true,
    'appointment_id',v_id,
    'final_total',v_final,
    'discount_code',nullif(v_code,''),
    'discount_percent',v_discount
  );
end;
$$;

grant execute on function public.create_residential_booking(
  text,date,text,text,text,text,numeric,text,jsonb
) to anon, authenticated;
