-- GLEMI visual website editor
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  page text not null,
  element_key text not null,
  content_type text not null check (content_type in ('text','image','link','placeholder')),
  value text,
  extra_value text,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique(page, element_key)
);

alter table public.site_content enable row level security;

drop policy if exists site_content_public_read on public.site_content;
create policy site_content_public_read on public.site_content
for select to anon, authenticated
using (true);

drop policy if exists site_content_admin_insert on public.site_content;
create policy site_content_admin_insert on public.site_content
for insert to authenticated
with check (public.is_glemi_admin());

drop policy if exists site_content_admin_update on public.site_content;
create policy site_content_admin_update on public.site_content
for update to authenticated
using (public.is_glemi_admin())
with check (public.is_glemi_admin());

drop policy if exists site_content_admin_delete on public.site_content;
create policy site_content_admin_delete on public.site_content
for delete to authenticated
using (public.is_glemi_admin());

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('site-media','site-media',true,10485760,array['image/jpeg','image/png','image/webp','image/gif','image/avif'])
on conflict (id) do update set public=true;

drop policy if exists site_media_admin_insert on storage.objects;
create policy site_media_admin_insert on storage.objects
for insert to authenticated
with check (bucket_id='site-media' and public.is_glemi_admin());

drop policy if exists site_media_admin_update on storage.objects;
create policy site_media_admin_update on storage.objects
for update to authenticated
using (bucket_id='site-media' and public.is_glemi_admin())
with check (bucket_id='site-media' and public.is_glemi_admin());

drop policy if exists site_media_admin_delete on storage.objects;
create policy site_media_admin_delete on storage.objects
for delete to authenticated
using (bucket_id='site-media' and public.is_glemi_admin());
